#!/bin/bash

# Manual Testing Guide for IntermodalFreightEnv
# Follow these steps in order, each in a separate terminal/tab

echo "🚀 MANUAL TESTING GUIDE"
echo "======================="
echo ""
echo "Follow these steps in separate terminals/tabs:"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 1: Start Backend API Server"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Run this command:"
echo ""
echo "  /home/harsh/CodeWithHarsh/ML\ Projects/IntermodalFreightEnv/.venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
echo ""
echo "Expected output:"
echo "  INFO:     Uvicorn running on http://0.0.0.0:8000"
echo "  INFO:     Application startup complete"
echo ""
echo "✅ Keep this terminal RUNNING"
echo ""
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 2: Test API Endpoints"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Once backend is running, test these endpoints:"
echo ""
echo "1️⃣  Check Health:"
echo "    curl http://localhost:8000/health"
echo ""
echo "2️⃣  Get Tasks:"
echo "    curl http://localhost:8000/tasks"
echo ""
echo "3️⃣  Reset Environment:"
echo "    curl -X POST http://localhost:8000/reset \\
      -H 'Content-Type: application/json' \\
      -d '{\"task_id\": 1}'"
echo ""
echo "4️⃣  Grade a Trajectory:"
echo "    curl -X POST http://localhost:8000/grader \\
      -H 'Content-Type: application/json' \\
      -d '{\"task_id\": 1, \"trajectory\": [{\"action\": \"test\", \"observation\": {}}]}'"
echo ""
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TERMINAL 3: Start Frontend Dashboard"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Once backend is running, run this:"
echo ""
echo "  /home/harsh/CodeWithHarsh/ML\ Projects/IntermodalFreightEnv/.venv/bin/python -m streamlit run frontend/dashboard.py --server.port=8501"
echo ""
echo "Expected output:"
echo "  You can now view your Streamlit app in your browser."
echo "  Local URL: http://localhost:8501"
echo ""
echo "✅ Open browser to http://localhost:8501"
echo ""
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TESTING CHECKLIST (Frontend)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Once dashboard loads, test these features:"
echo ""
echo "☐ Sidebar Configuration"
echo "  ☐ API URL shows http://localhost:8000"
echo "  ☐ Health status shows ✅ (green)"
echo "  ☐ Can select Task 1, 2, or 3"
echo "  ☐ Can toggle 'Use fixed seed'"
echo "  ☐ Reset button is clickable"
echo ""
echo "☐ Task Selection"
echo "  ☐ Select Task 1 → Click Reset → See state"
echo "  ☐ Metrics show: Time, Cost, Carbon, Weight"
echo "  ☐ Task details expand to show name/description"
echo ""
echo "☐ Trajectory Submission"
echo "  ☐ Paste in trajectory:"
echo "    [{\"action\": \"test_move\", \"observation\": {}}]"
echo "  ☐ Click 'Grade Trajectory'"
echo "  ☐ See score appear in Grading Results"
echo "  ☐ See metrics display (hours, cost, carbon)"
echo ""
echo "☐ Multi-Task Testing"
echo "  ☐ Switch to Task 2 → Reset"
echo "  ☐ Submit trajectory → See score"
echo "  ☐ Switch to Task 3 → Reset"
echo "  ☐ Submit trajectory → See score"
echo ""
echo "☐ Reproducibility (Optional)"
echo "  ☐ Enable 'Use fixed seed'"
echo "  ☐ Set seed to 42"
echo "  ☐ Reset environment → Note state"
echo "  ☐ Reset again with same seed → Verify same state"
echo ""
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "❌ Backend won't start:"
echo "  → Check: lsof -i :8000  (see what's using port)"
echo "  → Kill:  kill -9 <PID>"
echo "  → Retry: Run backend command again"
echo ""
echo "❌ 'API Disconnected' in dashboard:"
echo "  → Verify backend is running in Terminal 1"
echo "  → Check URL in sidebar: http://localhost:8000"
echo "  → Test manually: curl http://localhost:8000/health"
echo ""
echo "❌ Frontend won't start:"
echo "  → Run: /home/harsh/.../python -m streamlit run frontend/dashboard.py"
echo "  → Check: Is port 8501 available? (lsof -i :8501)"
echo ""
echo "❌ Trajectory submission fails:"
echo "  → Verify JSON is valid (use jsonlint.com)"
echo "  → Check backend logs in Terminal 1"
echo ""
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "Done testing? Here are the next steps:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ All tests pass → Ready for demo"
echo "✅ Take screenshots of dashboard"
echo "✅ Prepare judges' presentation"
echo "✅ Or submit for evaluation"
echo ""
